templateContent: Hello, %s!


# Database settings.
database:
  driverClass: org.postgresql.Driver

  user: gbhzuaikmocqdq
  password: 6hVRKHLWAEPHTQdiiv-MZS87_P

  url: jdbc:postgresql://ec2-54-217-215-81.eu-west-1.compute.amazonaws.com/dapabifj7v05rp?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory


# Server settings.
server:
  type: simple
  applicationContextPath: /
  connector:
    type: http


# Logging settings.
logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO

  # Logger-specific levels.
  loggers:

    com.example.helloworld: INFO

    org.hibernate.SQL: ALL

  appenders:
    - type: console
